name: timerow-build-deploy

on:
  push:
    branches:
      - master
    
permissions:
  contents: write
  pages: write
  id-token: write
      
jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          python-version: 3.10.14
          activate-environment: timerow
          auto-activate-base: false
      - run: |
          conda env list
          conda activate timerow
          conda list
      - name: Run Python code
        run: python main.py
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: output

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
